# Generated by Django 3.2.9 on 2021-11-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(max_length=300),
        ),
    ]
