# Generated by Django 3.2.9 on 2021-12-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211130_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
    ]
